cloudnative-amsterdam/kcd-utrecht-website

- src/components/pages/home/hero/hero.jsx
Add button to ticketing on homepage, currently links to cncf.io
> chore: ticketing button

- src/components/pages/archive/sponsors/sponsors.jsx
removed the sponsors from kcd zurich
> chore: remove sponsors

- src/components/pages/home/partners/partners.jsx
removed the media partners from kcd zurich
> chore: remove media partners

- src/components/pages/home/hero/hero.jsx
Added button to homepage with link to CFP
> chore: add CFP button to homepage

- src/components/pages/schedule/hero/hero.jsx
- src/components/pages/schedule/schedule/schedule.jsx
- src/constants/menus.js
removed schedule, put in place a tba message, fixed date and text in schedule page hero.
> chore: cleanup schedule page

- src/components/shared/footer/footer.jsx
- src/constants/links.js
> fix: remove kcd zurich logo from footer, readd linkedin link

- src/constants/links.js
Received the ticket url that will be used, configured it in the constants.
> chore: add correct ticket url

- src/components/shared/sponsors/sponsors.jsx
> add sponsor prospectus link

- src/components/pages/schedule/hero/hero.jsx
UPdate hero text with info about one track and maybe two instead of advertising two.
> chore: update schedule hero text

- src/constants/links.js
update maps location link to location defined on the ticketing website.
> chore: update maps location link

- src/constants/links.js
> chore: update linkedin to cloudnative nl

- src/components/pages/schedule/schedule/schedule.jsx
> chore: update schedule

- src/components/pages/home/venue/venue.jsx
adds date and location to homepage.
> chore: add date and location to homepage

- src/components/shared/sponsors/sponsors.jsx
- src/icons/fullstaq.svg
> chore: add fullstaq sponsor

- src/components/shared/sponsors/sponsors.jsx
> chore: add isovalent sponsor

- src/components/pages/home/hero/hero.jsx
- src/components/pages/schedule/hero/hero.jsx
Removed CFP button from schedule and homepage.
> chore: remove cfp link

- src/components/shared/header/header.jsx
Made the header logo responsive by adding md selector to change logo height.
> feat: size header logo responsively

- src/components/pages/schedule/schedule/schedule.jsx
- Fix schedule talk that was at 11:20 to 11:15
- Cleaner abstract for closing keynote (none available yet)
- Update cpet talk absract and title used for dutch government org
> Fix schedule timing and add abstracts

- src/components/pages/schedule/schedule/schedule.jsx
Updated talk title for Guiseppe
> chore: talk title updated for guiseppe

- src/components/pages/archive/podcast/podcast.jsx
Fixed build issue (changed jpg to png).
> fix: use correct podcast logo file

- src/components/shared/sponsors/sponsors.jsx
> fix: use correct paloalto link

- src/components/pages/schedule/schedule/schedule.jsx
updated title and abstract for sevi's talk
> chore: updated title and abstract for sevi's talk

- src/components/pages/schedule/schedule/schedule.jsx
Made breaks 5min to extend morning and afternoon breaks.
> chore: make morning/afternoon breaks longer and shorten short breaks
